/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CardNotFoundRouteImport } from './routes/card-not-found'
import { Route as AuthenticatedBriefingRouteImport } from './routes/_authenticated/briefing'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AuthenticatedLeadAttendeeIdRouteImport } from './routes/_authenticated/lead.$attendeeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CardNotFoundRoute = CardNotFoundRouteImport.update({
  id: '/card-not-found',
  path: '/card-not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBriefingRoute = AuthenticatedBriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeadAttendeeIdRoute =
  AuthenticatedLeadAttendeeIdRouteImport.update({
    id: '/lead/$attendeeId',
    path: '/lead/$attendeeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/card-not-found': typeof CardNotFoundRoute
  '/briefing': typeof AuthenticatedBriefingRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/c/$token': typeof CTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/lead/$attendeeId': typeof AuthenticatedLeadAttendeeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/card-not-found': typeof CardNotFoundRoute
  '/briefing': typeof AuthenticatedBriefingRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/c/$token': typeof CTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/lead/$attendeeId': typeof AuthenticatedLeadAttendeeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/card-not-found': typeof CardNotFoundRoute
  '/_authenticated/briefing': typeof AuthenticatedBriefingRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/c/$token': typeof CTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/_authenticated/lead/$attendeeId': typeof AuthenticatedLeadAttendeeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/card-not-found'
    | '/briefing'
    | '/leads'
    | '/scan'
    | '/c/$token'
    | '/p/$slug'
    | '/lead/$attendeeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/card-not-found'
    | '/briefing'
    | '/leads'
    | '/scan'
    | '/c/$token'
    | '/p/$slug'
    | '/lead/$attendeeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/card-not-found'
    | '/_authenticated/briefing'
    | '/_authenticated/leads'
    | '/_authenticated/scan'
    | '/c/$token'
    | '/p/$slug'
    | '/_authenticated/lead/$attendeeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CardNotFoundRoute: typeof CardNotFoundRoute
  CTokenRoute: typeof CTokenRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card-not-found': {
      id: '/card-not-found'
      path: '/card-not-found'
      fullPath: '/card-not-found'
      preLoaderRoute: typeof CardNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/briefing': {
      id: '/_authenticated/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof AuthenticatedBriefingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lead/$attendeeId': {
      id: '/_authenticated/lead/$attendeeId'
      path: '/lead/$attendeeId'
      fullPath: '/lead/$attendeeId'
      preLoaderRoute: typeof AuthenticatedLeadAttendeeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBriefingRoute: typeof AuthenticatedBriefingRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedLeadAttendeeIdRoute: typeof AuthenticatedLeadAttendeeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBriefingRoute: AuthenticatedBriefingRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedLeadAttendeeIdRoute: AuthenticatedLeadAttendeeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CardNotFoundRoute: CardNotFoundRoute,
  CTokenRoute: CTokenRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
