/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CardNotFoundRouteImport } from './routes/card-not-found'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedBriefingRouteImport } from './routes/_authenticated/briefing'
import { Route as AuthenticatedBroadcastRouteImport } from './routes/_authenticated/broadcast'
import { Route as AuthenticatedDubRouteImport } from './routes/_authenticated/dub'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as JoinSessionIdRouteImport } from './routes/join.$sessionId'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AuthenticatedActivateSessionIdRouteImport } from './routes/_authenticated/activate.$sessionId'
import { Route as AuthenticatedLeadAttendeeIdRouteImport } from './routes/_authenticated/lead.$attendeeId'
import { Route as AuthenticatedSignupSessionIdRouteImport } from './routes/_authenticated/signup.$sessionId'
import { Route as ApiPublicWebhooksMembershipRouteImport } from './routes/api/public/webhooks/membership'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CardNotFoundRoute = CardNotFoundRouteImport.update({
  id: '/card-not-found',
  path: '/card-not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBriefingRoute = AuthenticatedBriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBroadcastRoute = AuthenticatedBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDubRoute = AuthenticatedDubRouteImport.update({
  id: '/dub',
  path: '/dub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinSessionIdRoute = JoinSessionIdRouteImport.update({
  id: '/join/$sessionId',
  path: '/join/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivateSessionIdRoute =
  AuthenticatedActivateSessionIdRouteImport.update({
    id: '/activate/$sessionId',
    path: '/activate/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadAttendeeIdRoute =
  AuthenticatedLeadAttendeeIdRouteImport.update({
    id: '/lead/$attendeeId',
    path: '/lead/$attendeeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSignupSessionIdRoute =
  AuthenticatedSignupSessionIdRouteImport.update({
    id: '/signup/$sessionId',
    path: '/signup/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksMembershipRoute =
  ApiPublicWebhooksMembershipRouteImport.update({
    id: '/api/public/webhooks/membership',
    path: '/api/public/webhooks/membership',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/card-not-found': typeof CardNotFoundRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/briefing': typeof AuthenticatedBriefingRoute
  '/broadcast': typeof AuthenticatedBroadcastRoute
  '/dub': typeof AuthenticatedDubRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/scan': typeof AuthenticatedScanRoute
  '/c/$token': typeof CTokenRoute
  '/join/$sessionId': typeof JoinSessionIdRoute
  '/p/$slug': typeof PSlugRoute
  '/activate/$sessionId': typeof AuthenticatedActivateSessionIdRoute
  '/lead/$attendeeId': typeof AuthenticatedLeadAttendeeIdRoute
  '/signup/$sessionId': typeof AuthenticatedSignupSessionIdRoute
  '/api/public/webhooks/membership': typeof ApiPublicWebhooksMembershipRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/card-not-found': typeof CardNotFoundRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/briefing': typeof AuthenticatedBriefingRoute
  '/broadcast': typeof AuthenticatedBroadcastRoute
  '/dub': typeof AuthenticatedDubRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/scan': typeof AuthenticatedScanRoute
  '/c/$token': typeof CTokenRoute
  '/join/$sessionId': typeof JoinSessionIdRoute
  '/p/$slug': typeof PSlugRoute
  '/activate/$sessionId': typeof AuthenticatedActivateSessionIdRoute
  '/lead/$attendeeId': typeof AuthenticatedLeadAttendeeIdRoute
  '/signup/$sessionId': typeof AuthenticatedSignupSessionIdRoute
  '/api/public/webhooks/membership': typeof ApiPublicWebhooksMembershipRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/card-not-found': typeof CardNotFoundRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/briefing': typeof AuthenticatedBriefingRoute
  '/_authenticated/broadcast': typeof AuthenticatedBroadcastRoute
  '/_authenticated/dub': typeof AuthenticatedDubRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/c/$token': typeof CTokenRoute
  '/join/$sessionId': typeof JoinSessionIdRoute
  '/p/$slug': typeof PSlugRoute
  '/_authenticated/activate/$sessionId': typeof AuthenticatedActivateSessionIdRoute
  '/_authenticated/lead/$attendeeId': typeof AuthenticatedLeadAttendeeIdRoute
  '/_authenticated/signup/$sessionId': typeof AuthenticatedSignupSessionIdRoute
  '/api/public/webhooks/membership': typeof ApiPublicWebhooksMembershipRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/card-not-found'
    | '/admin'
    | '/automations'
    | '/briefing'
    | '/broadcast'
    | '/dub'
    | '/leads'
    | '/pipeline'
    | '/scan'
    | '/c/$token'
    | '/join/$sessionId'
    | '/p/$slug'
    | '/activate/$sessionId'
    | '/lead/$attendeeId'
    | '/signup/$sessionId'
    | '/api/public/webhooks/membership'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/card-not-found'
    | '/admin'
    | '/automations'
    | '/briefing'
    | '/broadcast'
    | '/dub'
    | '/leads'
    | '/pipeline'
    | '/scan'
    | '/c/$token'
    | '/join/$sessionId'
    | '/p/$slug'
    | '/activate/$sessionId'
    | '/lead/$attendeeId'
    | '/signup/$sessionId'
    | '/api/public/webhooks/membership'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/card-not-found'
    | '/_authenticated/admin'
    | '/_authenticated/automations'
    | '/_authenticated/briefing'
    | '/_authenticated/broadcast'
    | '/_authenticated/dub'
    | '/_authenticated/leads'
    | '/_authenticated/pipeline'
    | '/_authenticated/scan'
    | '/c/$token'
    | '/join/$sessionId'
    | '/p/$slug'
    | '/_authenticated/activate/$sessionId'
    | '/_authenticated/lead/$attendeeId'
    | '/_authenticated/signup/$sessionId'
    | '/api/public/webhooks/membership'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CardNotFoundRoute: typeof CardNotFoundRoute
  CTokenRoute: typeof CTokenRoute
  JoinSessionIdRoute: typeof JoinSessionIdRoute
  PSlugRoute: typeof PSlugRoute
  ApiPublicWebhooksMembershipRoute: typeof ApiPublicWebhooksMembershipRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card-not-found': {
      id: '/card-not-found'
      path: '/card-not-found'
      fullPath: '/card-not-found'
      preLoaderRoute: typeof CardNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/briefing': {
      id: '/_authenticated/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof AuthenticatedBriefingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/broadcast': {
      id: '/_authenticated/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof AuthenticatedBroadcastRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dub': {
      id: '/_authenticated/dub'
      path: '/dub'
      fullPath: '/dub'
      preLoaderRoute: typeof AuthenticatedDubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$sessionId': {
      id: '/join/$sessionId'
      path: '/join/$sessionId'
      fullPath: '/join/$sessionId'
      preLoaderRoute: typeof JoinSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activate/$sessionId': {
      id: '/_authenticated/activate/$sessionId'
      path: '/activate/$sessionId'
      fullPath: '/activate/$sessionId'
      preLoaderRoute: typeof AuthenticatedActivateSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lead/$attendeeId': {
      id: '/_authenticated/lead/$attendeeId'
      path: '/lead/$attendeeId'
      fullPath: '/lead/$attendeeId'
      preLoaderRoute: typeof AuthenticatedLeadAttendeeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/signup/$sessionId': {
      id: '/_authenticated/signup/$sessionId'
      path: '/signup/$sessionId'
      fullPath: '/signup/$sessionId'
      preLoaderRoute: typeof AuthenticatedSignupSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/membership': {
      id: '/api/public/webhooks/membership'
      path: '/api/public/webhooks/membership'
      fullPath: '/api/public/webhooks/membership'
      preLoaderRoute: typeof ApiPublicWebhooksMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedBriefingRoute: typeof AuthenticatedBriefingRoute
  AuthenticatedBroadcastRoute: typeof AuthenticatedBroadcastRoute
  AuthenticatedDubRoute: typeof AuthenticatedDubRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedActivateSessionIdRoute: typeof AuthenticatedActivateSessionIdRoute
  AuthenticatedLeadAttendeeIdRoute: typeof AuthenticatedLeadAttendeeIdRoute
  AuthenticatedSignupSessionIdRoute: typeof AuthenticatedSignupSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedBriefingRoute: AuthenticatedBriefingRoute,
  AuthenticatedBroadcastRoute: AuthenticatedBroadcastRoute,
  AuthenticatedDubRoute: AuthenticatedDubRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedActivateSessionIdRoute: AuthenticatedActivateSessionIdRoute,
  AuthenticatedLeadAttendeeIdRoute: AuthenticatedLeadAttendeeIdRoute,
  AuthenticatedSignupSessionIdRoute: AuthenticatedSignupSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CardNotFoundRoute: CardNotFoundRoute,
  CTokenRoute: CTokenRoute,
  JoinSessionIdRoute: JoinSessionIdRoute,
  PSlugRoute: PSlugRoute,
  ApiPublicWebhooksMembershipRoute: ApiPublicWebhooksMembershipRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
