-- Phase 1 event signup orchestration. Field Hub remains the system of record for
-- booth attribution and the main TCPC site remains the membership authority.
CREATE TYPE public.signup_session_status AS ENUM (
  'CREATED',
  'QR_SCANNED',
  'CHECKOUT_STARTED',
  'MEMBERSHIP_ACTIVE',
  'CARD_ISSUED',
  'EXPIRED',
  'CANCELLED'
);

CREATE TABLE public.signup_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  public_id text NOT NULL UNIQUE DEFAULT (
    'FH-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10))
  ),
  lead_id uuid NOT NULL REFERENCES public.leads(id) ON DELETE RESTRICT,
  badge_lead_id text NOT NULL,
  event_id text NOT NULL,
  scanned_by_staff_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  attributed_to_staff_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_by_staff_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  card_issued_by_staff_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  staff_device_id text NOT NULL,
  staff_session_id text NOT NULL,
  dub_partner_id text,
  dub_link_id text,
  status public.signup_session_status NOT NULL DEFAULT 'CREATED',
  join_url text NOT NULL,
  tax_comp_pro_user_id text,
  membership_id text,
  membership_plan text,
  membership_status text,
  integration_reference text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  qr_scanned_at timestamptz,
  checkout_started_at timestamptz,
  completed_at timestamptz,
  last_membership_check_at timestamptz,
  card_issued_at timestamptz,
  CONSTRAINT membership_active_has_identity CHECK (
    status NOT IN ('MEMBERSHIP_ACTIVE', 'CARD_ISSUED')
    OR (
      tax_comp_pro_user_id IS NOT NULL
      AND membership_status = 'ACTIVE'
      AND completed_at IS NOT NULL
    )
  ),
  CONSTRAINT card_issued_has_issuer CHECK (
    status <> 'CARD_ISSUED'
    OR (card_issued_by_staff_id IS NOT NULL AND card_issued_at IS NOT NULL)
  )
);

CREATE INDEX signup_sessions_event_created_idx
  ON public.signup_sessions (event_id, created_at DESC);
CREATE INDEX signup_sessions_scanned_by_created_idx
  ON public.signup_sessions (scanned_by_staff_id, created_at DESC);
CREATE INDEX signup_sessions_attributed_to_created_idx
  ON public.signup_sessions (attributed_to_staff_id, created_at DESC);
CREATE INDEX signup_sessions_status_event_idx
  ON public.signup_sessions (status, event_id);

CREATE TABLE public.signup_session_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signup_session_id uuid NOT NULL REFERENCES public.signup_sessions(id) ON DELETE CASCADE,
  from_status public.signup_session_status,
  to_status public.signup_session_status NOT NULL,
  actor_staff_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  source text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX signup_session_events_session_created_idx
  ON public.signup_session_events (signup_session_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.audit_signup_session_status()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.signup_session_events (
      signup_session_id, from_status, to_status, actor_staff_id, source
    ) VALUES (NEW.id, NULL, NEW.status, NEW.created_by_staff_id, 'FIELD_HUB');
  ELSIF NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO public.signup_session_events (
      signup_session_id, from_status, to_status, actor_staff_id, source
    ) VALUES (
      NEW.id,
      OLD.status,
      NEW.status,
      CASE WHEN NEW.status = 'CARD_ISSUED' THEN NEW.card_issued_by_staff_id ELSE NULL END,
      CASE WHEN NEW.status = 'CARD_ISSUED' THEN 'FIELD_HUB' ELSE 'TAX_COMP_PRO' END
    );
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.protect_signup_session_attribution()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  old_rank integer;
  new_rank integer;
BEGIN
  IF NEW.scanned_by_staff_id IS DISTINCT FROM OLD.scanned_by_staff_id
    OR NEW.attributed_to_staff_id IS DISTINCT FROM OLD.attributed_to_staff_id
    OR NEW.created_by_staff_id IS DISTINCT FROM OLD.created_by_staff_id
    OR NEW.dub_partner_id IS DISTINCT FROM OLD.dub_partner_id
    OR NEW.dub_link_id IS DISTINCT FROM OLD.dub_link_id
    OR NEW.badge_lead_id IS DISTINCT FROM OLD.badge_lead_id
    OR NEW.event_id IS DISTINCT FROM OLD.event_id THEN
    RAISE EXCEPTION 'Original signup attribution cannot be changed';
  END IF;

  old_rank := CASE OLD.status
    WHEN 'CREATED' THEN 0
    WHEN 'QR_SCANNED' THEN 1
    WHEN 'CHECKOUT_STARTED' THEN 2
    WHEN 'MEMBERSHIP_ACTIVE' THEN 3
    WHEN 'CARD_ISSUED' THEN 4
    ELSE 5
  END;
  new_rank := CASE NEW.status
    WHEN 'CREATED' THEN 0
    WHEN 'QR_SCANNED' THEN 1
    WHEN 'CHECKOUT_STARTED' THEN 2
    WHEN 'MEMBERSHIP_ACTIVE' THEN 3
    WHEN 'CARD_ISSUED' THEN 4
    ELSE 5
  END;

  IF new_rank < old_rank THEN
    RAISE EXCEPTION 'Signup status cannot move backward';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER signup_sessions_set_updated_at
  BEFORE UPDATE ON public.signup_sessions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER signup_sessions_protect_attribution
  BEFORE UPDATE ON public.signup_sessions
  FOR EACH ROW EXECUTE FUNCTION public.protect_signup_session_attribution();

CREATE TRIGGER signup_sessions_audit_status
  AFTER INSERT OR UPDATE ON public.signup_sessions
  FOR EACH ROW EXECUTE FUNCTION public.audit_signup_session_status();

-- The card action is the only staff-side state transition after checkout. The
-- function is intentionally atomic and refuses inactive or incomplete members.
CREATE OR REPLACE FUNCTION public.issue_proconnect_card(_signup_session_id uuid)
RETURNS public.signup_sessions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  result public.signup_sessions;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  UPDATE public.signup_sessions
  SET
    status = 'CARD_ISSUED',
    card_issued_by_staff_id = auth.uid(),
    card_issued_at = now()
  WHERE id = _signup_session_id
    AND status = 'MEMBERSHIP_ACTIVE'
    AND membership_status = 'ACTIVE'
    AND tax_comp_pro_user_id IS NOT NULL
  RETURNING * INTO result;

  IF result.id IS NULL THEN
    RAISE EXCEPTION 'Active membership must be verified before card issuance';
  END IF;

  RETURN result;
END;
$$;

-- Keep the legacy lead indicator accurate while older screens still use it.
CREATE OR REPLACE FUNCTION public.sync_lead_membership_flag()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.status IN ('MEMBERSHIP_ACTIVE', 'CARD_ISSUED') THEN
    UPDATE public.leads SET joined_tcpc = true WHERE id = NEW.lead_id;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER signup_sessions_sync_lead_membership
  AFTER INSERT OR UPDATE OF status ON public.signup_sessions
  FOR EACH ROW EXECUTE FUNCTION public.sync_lead_membership_flag();

GRANT SELECT, INSERT ON public.signup_sessions TO authenticated;
GRANT SELECT ON public.signup_session_events TO authenticated;
GRANT ALL ON public.signup_sessions, public.signup_session_events TO service_role;
REVOKE ALL ON FUNCTION public.issue_proconnect_card(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.issue_proconnect_card(uuid) TO authenticated;

ALTER TABLE public.signup_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signup_session_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Staff can view all signup sessions" ON public.signup_sessions
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "Staff can create attributed signup sessions" ON public.signup_sessions
  FOR INSERT TO authenticated
  WITH CHECK (
    auth.uid() = created_by_staff_id
    AND scanned_by_staff_id = attributed_to_staff_id
    AND EXISTS (
      SELECT 1
      FROM public.leads
      WHERE leads.id = signup_sessions.lead_id
        AND leads.scanned_by = signup_sessions.scanned_by_staff_id
    )
  );
CREATE POLICY "Staff can view signup session events" ON public.signup_session_events
  FOR SELECT TO authenticated USING (true);
